backend:
  name: git-gateway
  branch: main

media_folder: public/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: '文章標題'
        name: title
        widget: string
      - label: '文章時間'
        name: date
        widget: datetime
      - label: '封面圖片'
        name: cover
        widget: image
        required: false
      - label: '文章說明文字'
        name: description
        widget: string
      - label: '標籤'
        name: tags
        widget: list
      - label: '作者'
        name: author
        widget: select
        options: ['Chambers', 'Sandra']
      - label: '內文'
        name: body
        widget: markdown